In [ ]:
### `1.` Create an array of integers from 25 to 2 with step of -2

In [3]:
import numpy as np
arr=np.arange(25,1,-2)
arr

array([25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3])

In [ ]:
### `2.` Find the minium value along each of the rows.

In [5]:
num_array = np.random.randint(100, 200,12).reshape(4,3)

In [7]:
num_array

array([[186, 111, 148],
       [103, 136, 199],
       [194, 193, 193],
       [107, 121, 175]])

In [31]:
# Find the minimum along each row
row_minima = np.min(num_array, axis=1)

print(row_minima)


[111 103 193 107]


In [ ]:
### `3.` Replace all odd number in the array with -2 (Create an array by yoursefl)

In [53]:
custom_array=np.arange(1,25)
custom_array
# Replace odd numbers with -2
custom_array[custom_array % 2 != 0] = -2
print(custom_array)


[-2  2 -2  4 -2  6 -2  8 -2 10 -2 12 -2 14 -2 16 -2 18 -2 20 -2 22 -2 24]


24

In [ ]:
### `4.` Stack two array vertically (Create an array by yourself)

In [65]:
import numpy as np

# Create random arrays
array1 = np.random.randint(1, 20, size=(2, 3))
array2 = np.random.randint(10, 20, size=(2, 3))
stacked_array = np.vstack((array1, array2))
print(array1)
print(array2)
print("the vertically stacked array is:")
print(stacked_array)

[[17  2 12]
 [14 16  1]]
[[16 16 15]
 [16 19 13]]
the vertically stacked array is:
[[17  2 12]
 [14 16  1]
 [16 16 15]
 [16 19 13]]


In [ ]:
### `5.` Remove all the elements from first array that are present in second array.

In [81]:
import numpy as np

# Create two arrays (example)
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([2, 4, 6])

# Remove elements of array2 from array1
result = np.setdiff1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Result after removal:", result)

Array 1: [1 2 3 4 5 6]
Array 2: [2 4 6]
Result after removal: [1 3 5]


In [ ]:
### `6.` Get the position where elements of two arrays match

In [83]:
import numpy as np

# Create two arrays (example)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 2, 3, 8, 1])

# Find positions where elements match
matching_indices = np.where(array1 == array2)[0]

print("Array 1:", array1)
print("Array 2:", array2)
print("Matching indices:", matching_indices)

Array 1: [1 2 3 4 5]
Array 2: [5 2 3 8 1]
Matching indices: [1 2]


In [ ]:
### `7.` Reverse each of the rows of the 2D array

In [93]:
import numpy as np

arr = np.arange(1,7).reshape(2,3)
print("Original array:")
print(arr)

# Reverse each row
reverse_rows = arr[:, ::-1]  # Correct way

print("\nReversed rows:")
print(reverse_rows)

Original array:
[[1 2 3]
 [4 5 6]]

Reversed rows:
[[3 2 1]
 [6 5 4]]


In [ ]:
### `8.` Swap row 1 and row2 in given array

In [97]:
num_array = np.arange(9).reshape(3,3)
num_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
# Swap Row 1 and Row 2
num_array[[1, 2]] = num_array[[2, 1]]

print("\nArray after swapping Row 1 and Row 2:")
print(num_array)


Array after swapping Row 1 and Row 2:
[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [ ]:
### `9.` WAP to add a new column ([10,11]) at the last position in the array given below.

In [ ]:
arra = [[[3,4],[4,5],[7,8],[5,6]]]

In [ ]:
### `10.` How to combine the two array horizontally. Create any two array with 2D.

In [ ]:



import numpy as np



#data for student performance

modules_completed = np.array([12, 15, 18, 20, 14, 16, 22, 10, 13, 17, 19, 21, 14, 12, 16, 18, 20, 14, 16, 19])

quiz_scores = np.array([85, 90, 78, 92, 88, 76, 95, 80, 89, 94, 81, 87, 93, 79, 91, 84, 88, 75, 82, 96])
#count=np.sum(modules_completed>15)
#print(count)
#avg=np.mean(quiz_scores)
#print(avg)
#What percentage of students scored below 80 in the quiz?
below_quiz=np.percentage(quiz_scores<80)
print(below_quiz)