# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

### Numpy vs Lists 

In [5]:
# intialise a list with the following elements: 1, 2, 3, 4, 5
lst=[1, 2, 3, 4, 5]
lst

# try to multiply 2.5 directly to the created list

lst=[1, 2, 3, 4, 5]*2.5
lst

TypeError: can't multiply sequence by non-int of type 'float'

 multiply a list directly by a number in Python, it doesn't perform element-wise multiplication as you might expect.This will raise a TypeError because you can't multiply a list by a float - list repetition only works with integers.
you might want to use NumPy arrays which support element-wise operations:


Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [7]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np


In [11]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array

np_l = np.array([1, 2, 3, 4, 5])
np_l

array([1, 2, 3, 4, 5])

In [13]:
# Multiply each element with 2.5 

mul=np_l*2.5

In [15]:
# Print the result using the print command. Compare the structure of list and array.
print(mul)

[ 2.5  5.   7.5 10.  12.5]


In [31]:
# Create a 1-D array using with the elements (1, abc, True)
#my_list = [1, "abc", True]
#print(my_list)  #---> generl python approach
#Using a NumPy Array (For Numerical Work, but Mixed Types are Stored as Objects)
import numpy as np

my_array = np.array([1, "abc", True], dtype=object)
print(my_array)  # Output: [1 'abc' True]

#import pandas as pd

#my_series = pd.Series([1, "abc", True])
#print(my_series)

#Pandas Series is like a 1-D array but with more functionality, and it handles mixed types naturally.

[1 'abc' True]


You can see above that the elements are of single data type. The numerical and the boolean value is converted to string. 

### Operations over Arrays
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [33]:
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
list1 = (1, 2, 3)
list2 = (4, 5, 6)
sum=list1+list2

# Use the '+' operator and print the results
print(sum)


(1, 2, 3, 4, 5, 6)


In [35]:
# Convert the above lists to arrays and use the '+' operator

np_1 = np.array((1, 2, 3))
np_2 =np.array((4, 5, 6)) 
sum=np_1+np_2
sum


array([5, 7, 9])

You can look at the difference between the two outputs. We will look at different operations over NumPy arrays in detail in the coming segments.