# Introduction to NumPy
In this session, we will learn about the basics of NumPy, which is the fundamental package for mathematical computing in Python. **NumPy** stands for **Numerical Python**. The primary use of NumPy is efficient data handling and manipulation.

NumPy has inbuilt function for working with `numpy` objects. Here you will learn mainly about NumPy arrays which are a key class within NumPy. You will be introduced to some of it at the end of this session but will learn more about it in the coming weeks.

To access `numpy` and its function, import it in your Python code like this: `import numpy as np`.

In [ ]:
import numpy as np

# NumPy arrays
Arrays are the main ways of storing data when using the `numpy` library. We create these arrays using the `array()` method that instantiates an object of the `ndarray` class.

### Example
Creating empty arrays

In [ ]:
#np_arr = np.array()

In [ ]:
np_arr = np.array(object = [])
np_arr

array([], dtype=float64)

In [ ]:
np_arr = np.array([])
np_arr

array([], dtype=float64)

In [ ]:
type(np_arr)

numpy.ndarray

In [ ]:
print(np_arr)

[]


In [ ]:
len(np_arr)

0

### Example
Creating arrays from lists

In [ ]:
some_list = [1, 4, 5, 6]
some_list

[1, 4, 5, 6]

In [ ]:
type(some_list)

list

In [ ]:
np_arr = np.array(object = some_list)
np_arr

array([1, 4, 5, 6])

In [ ]:
type(np_arr)

numpy.ndarray

In [ ]:
np_arr[0]

1

In [ ]:
type(np_arr[0])

numpy.int64

In [ ]:
np_arr.dtype

dtype('int64')

In [ ]:
np_arr = np.array(['apple', 'orange', 'banana', 'watermelon', 'jackfruit'])
np_arr

array(['apple', 'orange', 'banana', 'watermelon', 'jackfruit'],
      dtype='<U10')

In [ ]:
type(np_arr)

numpy.ndarray

In [ ]:
np_arr[0]

'apple'

In [ ]:
type(np_arr[0])

numpy.str_

In [ ]:
np_arr.dtype

dtype('<U10')

The datatype `<U10` represents a **Unicode** string with a maximum length of 10 characters. To learn more about Unicode strings, you can checkout the official [documentation](https://https://docs.python.org/3/howto/unicode.html).

In [ ]:
np_arr = np.array(object = [1, 2, 3], dtype = 'int')
np_arr

array([1, 2, 3])

In [ ]:
np_arr = np.array(object = [1, 2, 3], dtype = 'float')
np_arr

array([1., 2., 3.])

In [ ]:
np_arr = np.array([-1, 5.5, 2, 3.5])
np_arr

array([-1. ,  5.5,  2. ,  3.5])

Note that the integers have been converted to floats. Arrays cannot be of composite data types.

In [ ]:
np_arr = np.array(['apple', 2, 'banana', 4.5])
np_arr

array(['apple', '2', 'banana', '4.5'], dtype='<U32')

Note that the numbers have been converted to strings. Arrays cannot be of composite data types.

Learners are encouraged to study and experiment with the `dtype` parameter further.

### Example
Creating arrays from tuples

In [ ]:
some_tuple = (-5, 1, -4, 7, 2)
print(some_tuple, type(some_tuple))

(-5, 1, -4, 7, 2) <class 'tuple'>


In [ ]:
np_arr = np.array(some_tuple)
print(np_arr, type(np_arr))

[-5  1 -4  7  2] <class 'numpy.ndarray'>


### Example
Creating arrays from sets

In [ ]:
some_set = {1.3, -5.6, 2.8, -6.2, 8.4}
print(some_set, type(some_set))

{1.3, 2.8, 8.4, -6.2, -5.6} <class 'set'>


In [ ]:
np_arr = np.array(some_set)
np_arr

array({1.3, 2.8, 8.4, -6.2, -5.6}, dtype=object)

Sets have no inherent ordering. So, it makes little sense to generate arrays from sets.

In [ ]:
# some_set[0]

In [ ]:
# np_arr[0]

In this section, we looked at an introduction to NumPy arrays and how we can create them from other data structures such as lists.

# Multidimensional arrays
One of NumPy's fundamental features is its ability to handle multidimensional arrays efficiently. A multidimensional array is an array with more than one dimension or axis.

### Example
Creating 2D arrays

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

Note that the object here is a list within a list, that is, a nested list with two levels.

Creating 3D arrays

In [ ]:
arr_3d = np.array([[[1, 5], [2, 7], [3, 9]], [[4, 8], [5, 11], [6, 13]]])
arr_3d

array([[[ 1,  5],
        [ 2,  7],
        [ 3,  9]],

       [[ 4,  8],
        [ 5, 11],
        [ 6, 13]]])

Note that the object here is a list within a list within a list, that is, a nested list with three levels.

### Quiz
Consider the list `[[0.4, 1.2, 0.5, 0.8, 2.1], [2.1, 2.2, 9.4, 3.1]]`. What happens when you convert it to a NumPy array?

In [ ]:
##### CODE HERE #####

What was the problem?

# NumPy array attributes
NumPy arrays are well-structured, well-designed, and complex data structures. It is important to study and look at these data structures through the lens of their attributes.

### Example
Looking at the number of dimensions or axes in arrays

In [ ]:
np_arr = np.array([[1, -1], [0, 1]])
np_arr

array([[ 1, -1],
       [ 0,  1]])

In [ ]:
np_arr.ndim

2

The `ndim` attribute tells you the number of dimensions in the array.

In [ ]:
np_arr = np.array([22, -19, 45, 'John', 'Dwivedi'])
np_arr.ndim

1

### Example
Looking at the shape of arrays

In [ ]:
np_arr = np.array(['apple', 'banana', 'cherry'])
np_arr

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [ ]:
np_arr.shape

(3,)

The `shape` attribute in NumPy returns a tuple that represents the dimensions of the array. It shows the size of the array along each dimension.

In [ ]:
len(np_arr.shape)

1

In [ ]:
np_arr.ndim

1

In [ ]:
np_arr = np.array([['apple', 'banana'], ['cherry', 'date']])
np_arr

array([['apple', 'banana'],
       ['cherry', 'date']], dtype='<U6')

In [ ]:
np_arr.shape

(2, 2)

In [ ]:
len(np_arr.shape)

2

In [ ]:
np_arr.ndim

2

### Example
Studying the lengths of arrays

In [ ]:
np_arr = np.array([0, 1, 2, 3, 4])
np_arr

array([0, 1, 2, 3, 4])

In [ ]:
len(np_arr)

5

In [ ]:
np_arr.size

5

In [ ]:
np_arr = np.array([[0, 1, 2, 3, 4], ['A', 'B', 'C', 'D', 'E']])
np_arr

array([['0', '1', '2', '3', '4'],
       ['A', 'B', 'C', 'D', 'E']], dtype='<U21')

In [ ]:
len(np_arr)

2

In [ ]:
np_arr.size

10

The `len()` method returns only the number of elements in the highest level of the array whereas the `size` attribute returns the total number of elements in the array.

### Quiz
Extract the shape of the array `quiz_arr = np.array([[2, 5, 3, 4], [1, 6, 4, 2], [7, 8, 4,1]])`.

In [1]:
##### CODE HERE #####

### Quiz
What is the shape of the array `np.array([2, 5, 3, 4])`?

In [2]:
##### CODE HERE #####

In this section, we looked at some basic attributes of NumPy arrays. We urge all learners to go through the documentations for more details. You are encouraged to explore this further.

# Accessing NumPy array elements
Elements can be accessed from arrays in various ways.

### Example
Accessing elements from 1D arrays

In [ ]:
np_arr = np.array([22, -36, 32, 47, 71, -45])
np_arr

array([ 22, -36,  32,  47,  71, -45])

In [ ]:
np_arr[2]

32

In [ ]:
np_arr[1:4]

array([-36,  32,  47])

In [ ]:
np_arr[[1, 2, 3]]

array([-36,  32,  47])

In [ ]:
np_arr[[1, 4, 5]]

array([-36,  71, -45])

In [ ]:
np_arr[2:]

array([ 32,  47,  71, -45])

In [ ]:
np_arr[2:6]

array([ 32,  47,  71, -45])

In [ ]:
np_arr[2:len(np_arr)]

array([ 32,  47,  71, -45])

In [ ]:
np_arr[:3]

array([ 22, -36,  32])

In [ ]:
np_arr[0:3]

array([ 22, -36,  32])

In [ ]:
np_arr[-1]

-45

In [ ]:
np_arr[:-1]

array([ 22, -36,  32,  47,  71])

In [ ]:
np_arr[:-2]

array([ 22, -36,  32,  47])

### Quiz
Eextract the element `'Bob'` from `ex_arr = np.array(['Adil', 'Bob', 'Chandra', 'Dheeraj', 'Eashwar'])`.

In [3]:
##### CODE HERE #####

### Quiz
Print the array `exam_arr = np.array(['Adil', 'Bob', 'Chandra', 'Dheeraj', 'Eashwar'])` while skipping one element at a time.

In [4]:
##### CODE HERE #####

### Quiz
Reverse the array `quiz_arr = np.array(['Adil', 'Bob', 'Chandra', 'Dheeraj', 'Eashwar'])`.

In [5]:
##### CODE HERE #####

### Example
Accessing elements from 2D arrays

In [ ]:
np_arr = np.array([['Python', 'R', 'C++'], [len('Python'), len('R'), len('C++')]])
np_arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U21')

In [ ]:
np_arr[0][0]

'Python'

In [ ]:
np_arr[0, 0]

'Python'

In [ ]:
np_arr[1][2]

'3'

In [ ]:
np_arr[1, 2]

'3'

In [ ]:
np_arr[0]

array(['Python', 'R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0].shape

(3,)

In [ ]:
np_arr[[0]]

array([['Python', 'R', 'C++']], dtype='<U21')

In [ ]:
np_arr[[0]].shape

(1, 3)

In [ ]:
np_arr[0:]

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U21')

In [ ]:
np_arr[0, :]

array(['Python', 'R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0, ]

array(['Python', 'R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0][:]

array(['Python', 'R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0][1:]

array(['R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0, 1:]

array(['R', 'C++'], dtype='<U21')

In [ ]:
np_arr[0][:2]

array(['Python', 'R'], dtype='<U21')

In [ ]:
np_arr[0, :2]

array(['Python', 'R'], dtype='<U21')

In [ ]:
np_arr[0, [0, 1]]

array(['Python', 'R'], dtype='<U21')

In [ ]:
np_arr[0, [0, 2]]

array(['Python', 'C++'], dtype='<U21')

### Example
Printing `'fig'` from the following numpy array:
```
str_arr = np.array(object = [['apple', 'banana', 'cherry'],
                             ['date', 'fig', 'grape'],
                             ['kiwi', 'lemon', 'mango']])
```

In [ ]:
str_arr = np.array(object = [['apple', 'banana', 'cherry'],
                             ['date', 'fig', 'grape'],
                             ['kiwi', 'lemon', 'mango']])

In [ ]:
print(str_arr[1][1])

fig


In [ ]:
print(str_arr[1, 1])

fig


### Example
Printing `'lemon'` from the following numpy array:
```
str_arr = np.array(object = [['apple', 'banana', 'cherry'],
                             ['date', 'fig', 'grape'],
                             ['kiwi', 'lemon', 'mango']])            
```

In [ ]:
print(str_arr[2][1])

lemon


In [ ]:
print(str_arr[2, 1])

lemon


### Example
Printing `['kiwi', 'lemon', 'mango']` from the following numpy array:
```
str_arr = np.array(object = [['apple', 'banana', 'cherry'],
                             ['date', 'fig', 'grape'],
                             ['kiwi', 'lemon', 'mango']])
```

In [ ]:
str_arr[2]

array(['kiwi', 'lemon', 'mango'], dtype='<U6')

In [ ]:
str_arr[2,]

array(['kiwi', 'lemon', 'mango'], dtype='<U6')

In [ ]:
str_arr[2, :]

array(['kiwi', 'lemon', 'mango'], dtype='<U6')

In [ ]:
str_arr[2][:]

array(['kiwi', 'lemon', 'mango'], dtype='<U6')

### Example
Accessing elements based on logical conditions

In [ ]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
np_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
np_arr[np_arr > 2]

array([3, 4, 5, 6])

In [ ]:
np_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_arr = np_arr[np_arr > 2]
np_arr

array([3, 4, 5, 6])

In [ ]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
np_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
np_arr < 5

array([[ True,  True,  True],
       [ True, False, False]])

In [ ]:
# np_arr > 2 and np_arr < 5

In [ ]:
# (np_arr > 2) and (np_arr < 5)

In [ ]:
# np_arr > 2 & np_arr < 5

In [ ]:
(np_arr > 2) & (np_arr < 5)

array([[False, False,  True],
       [ True, False, False]])

In [ ]:
np_arr[(np_arr > 2) & (np_arr < 5)]

array([3, 4])

In [ ]:
np_arr[(np_arr < 3) | (np_arr > 4)]

array([1, 2, 5, 6])

### Example
Let us see how to count the number of elements in the following array that are greater than 50:
```
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])
```

In [ ]:
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])
len(num_arr[num_arr > 50])

14

### Quiz
Count the number of elements in the following array that lie in the range $[50,70]$ (both inclusive):
```
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])
```

In [6]:
##### CODE HERE #####

### Example
Finding indices of values in arrays

In [ ]:
company_revenue = np.array([2450.67, 1872.34, 1098.44, 2001.64, 2167.23])
company_revenue

array([2450.67, 1872.34, 1098.44, 2001.64, 2167.23])

In [ ]:
company_revenue == 1872.34

array([False,  True, False, False, False])

In [ ]:
company_revenue[company_revenue == 1872.34]

array([1872.34])

In [ ]:
np.nonzero(company_revenue == 1872.34)

(array([1]),)

In [ ]:
np.where(company_revenue == 1872.34)

(array([1]),)

In [ ]:
company_revenue > 2000

array([ True, False, False,  True,  True])

In [ ]:
np.where(company_revenue > 2000)

(array([0, 3, 4]),)

In [ ]:
(company_revenue > 2000) & (company_revenue < 2100)

array([False, False, False,  True, False])

In [ ]:
np.where((company_revenue > 2000) & (company_revenue < 2100))

(array([3]),)

In [ ]:
monthly_rates = np.array([[0, 25, 45], [10, 16, 8], [4, 2, 12]])
monthly_rates

array([[ 0, 25, 45],
       [10, 16,  8],
       [ 4,  2, 12]])

In [ ]:
monthly_rates == 0

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.where(monthly_rates == 0)

(array([0]), array([0]))

In [ ]:
monthly_rates == 8

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [ ]:
np.where(monthly_rates == 8)

(array([1]), array([2]))

In [ ]:
monthly_rates > 10

array([[False,  True,  True],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.where(monthly_rates > 10)

(array([0, 0, 1, 2]), array([1, 2, 1, 2]))

In [ ]:
(monthly_rates > 10) & (monthly_rates < 25)

array([[False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.where((monthly_rates > 10) & (monthly_rates < 25))

(array([1, 2]), array([1, 2]))

In [ ]:
monthly_rates

array([[ 0, 25, 45],
       [10, 16,  8],
       [ 4,  2, 12]])

In [ ]:
np.where(monthly_rates == 0)

(array([0]), array([0]))

In [ ]:
np.where(monthly_rates > 25)

(array([0]), array([2]))

In [ ]:
np.where((monthly_rates >= 25) | (monthly_rates % 2 != 0))

(array([0, 0]), array([1, 2]))

In this section, we learned how to access elements from arrays. Learners are encouraged to explore further on their own.