# Operations on NumPy Arrays
One of NumPy's key features is the ability to perform efficient array or vector operations. These operations are crucial for scientific computing, data analysis, and machine learning tasks.

In [98]:
import numpy as np

# Array Manipulation

This section includes operations like adding, deleting, removing and replacing elements from an array.

### Example
Adding elements to 1D arrays

In [99]:
np_arr = np.array([1, 2, 3])
np_arr

array([1, 2, 3])

In [100]:
np.append(arr = np_arr, values = 4)

array([1, 2, 3, 4])

In [101]:
np_arr

array([1, 2, 3])

Notice that the operation did not persist in-place. Keep an eye out for operations that are in-place and those that are not-in-place.

In [102]:
np_arr = np.append(np_arr, 4)
np_arr

array([1, 2, 3, 4])

In [103]:
np_arr = np.append(np_arr, [5, 6])
np_arr

array([1, 2, 3, 4, 5, 6])

In [104]:
np_arr = np.append(np_arr, np.array([7, 8]))
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### Example
Removing elements from 1D arrays

In [105]:
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
np.delete(arr = np_arr, obj = 2)

array([1, 2, 4, 5, 6, 7, 8])

Notice that the `.delete()` method uses the index of the object to perform deletion.

In [107]:
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

Also notice that the original array is unchanged. So, the `.delete()` method is not in-place.

### Example
Replacing elements in 1D arrays

In [108]:
np_arr = np.array([0, 2, 4, 6, 8, 10, -8, -6, -4])
np_arr

array([ 0,  2,  4,  6,  8, 10, -8, -6, -4])

In [109]:
np_arr[1] = 5
np_arr

array([ 0,  5,  4,  6,  8, 10, -8, -6, -4])

In [110]:
# np_arr[1] = [-1, -2]

In [111]:
np_arr[0:2] = [-1, -2]
np_arr

array([-1, -2,  4,  6,  8, 10, -8, -6, -4])

In [112]:
np_arr[-2:] = np.array([100, 200])
np_arr

array([ -1,  -2,   4,   6,   8,  10,  -8, 100, 200])

### Quiz
Append `['banana', 'cherry']` to the array `np_arr = np.array(['apple', 'orange', 'lemon'])`.

In [113]:
##### CODE HERE #####

### Quiz
Delete `['apple', 'orange']` from the above array

In [114]:
##### CODE HERE #####

### Quiz
Replace `'cherry'` with `'grape'` in the above array

In [115]:
##### CODE HERE #####

### Example
Adding elements to 2D arrays

In [116]:
np_arr = np.array([[1, 2, 3, 4], [-4, -3, -2, -1]])
np_arr

array([[ 1,  2,  3,  4],
       [-4, -3, -2, -1]])

In [117]:
np_arr.shape

(2, 4)

In [118]:
np_arr = np.append(np_arr, 0)
np_arr

array([ 1,  2,  3,  4, -4, -3, -2, -1,  0])

In [119]:
np_arr.shape

(9,)

In [120]:
np_arr = np.array([[1, 2, 3, 4], [-4, -3, -2, -1]])
np_arr

array([[ 1,  2,  3,  4],
       [-4, -3, -2, -1]])

In [121]:
# np.append(np_arr, 0, axis = 0)

In [122]:
new_arr = np.array([-5, 2, 5, 7])
new_arr

array([-5,  2,  5,  7])

In [123]:
# np.append(np_arr, new_arr, axis = 0)

We need to use methods such as `.reshape()` to handle some of these operations. You will learn more about it later in the session.

### Example
Deleting elements from 2D arrays

In [124]:
np_arr = np.array([[4.7, 1.4, -4.6], [2.6, -1.2, -2], [6.6, -3.2, 4.9]])
np_arr

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [125]:
np.delete(np_arr, 0)

array([ 1.4, -4.6,  2.6, -1.2, -2. ,  6.6, -3.2,  4.9])

If you try to delete a subset from an array which is not similar in shape to the original array, then it cannot maintain its original shape.

In [126]:
np_arr

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [127]:
np.delete(np_arr, 0, axis = 0)

array([[ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [128]:
np_arr

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [129]:
np_arr = np.delete(np_arr, 0, axis = 0)
np_arr

array([[ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [130]:
np_arr = np.delete(np_arr, [0, 1], axis = 0)
np_arr

array([], shape=(0, 3), dtype=float64)

In [131]:
np_arr = np.array([[4.7, 1.4, -4.6], [2.6, -1.2, -2], [6.6, -3.2, 4.9]])
np_arr

array([[ 4.7,  1.4, -4.6],
       [ 2.6, -1.2, -2. ],
       [ 6.6, -3.2,  4.9]])

In [132]:
np_arr = np.delete(np_arr, 1, axis = 1)
np_arr

array([[ 4.7, -4.6],
       [ 2.6, -2. ],
       [ 6.6,  4.9]])

### Example
Replacing elements in 2D arrays

In [133]:
np_arr = np.array([['Abhinav', 'Bhaskar', 'Manisha'], ['EMP0046', 'EMP1218', 'EMP9453'], [42, 34, 27]])
np_arr

array([['Abhinav', 'Bhaskar', 'Manisha'],
       ['EMP0046', 'EMP1218', 'EMP9453'],
       ['42', '34', '27']], dtype='<U21')

In [134]:
np_arr[0] = ['Govinda', 'Jaspreet', 'Lavina']
np_arr

array([['Govinda', 'Jaspreet', 'Lavina'],
       ['EMP0046', 'EMP1218', 'EMP9453'],
       ['42', '34', '27']], dtype='<U21')

In [135]:
np_arr[:, 0] = ['Himani', 'EMP1677', 37]
np_arr

array([['Himani', 'Jaspreet', 'Lavina'],
       ['EMP1677', 'EMP1218', 'EMP9453'],
       ['37', '34', '27']], dtype='<U21')

In [136]:
np_arr[:, 1:]

array([['Jaspreet', 'Lavina'],
       ['EMP1218', 'EMP9453'],
       ['34', '27']], dtype='<U21')

In [137]:
# np_arr[:, 1:] = [['Priya', 'EMP4251', 22], ['Rashid', 'EMP8576', 26]]

We need to use methods such as `.reshape()` to work on advanced array manipulation tasks. You will learn how to solve this problem later in the session.

### Example
Concatenating and splitting arrays

In [138]:
arr_1 = np.array([[1, 2], [-4, 3], [2, -5]])
arr_1

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [139]:
arr_2 = np.array([[1, 2], [-4, 3], [2, -5]])
arr_2

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [140]:
np.concatenate((arr_1, arr_2), axis = 0)

array([[ 1,  2],
       [-4,  3],
       [ 2, -5],
       [ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [141]:
np.concatenate((arr_1, arr_2), axis = 1)

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [142]:
np_arr = np.concatenate((arr_1, arr_2), axis = 1)
np_arr

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [143]:
np.split(ary = np_arr, indices_or_sections = [1])

[array([[1, 2, 1, 2]]),
 array([[-4,  3, -4,  3],
        [ 2, -5,  2, -5]])]

### Quiz
You are given two $2$x$3$ NumPy arrays:
```
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
```
Concatenate these arrays vertically to create a $4$x$3$ array

In [144]:
##### CODE HERE #####

In [145]:
##### CODE HERE #####

# Arithematic Operations

This section involves mathematical operations applied to arrays, such as vector addition, multiplication.

### Example
Performing vector addition with arrays

In [146]:
company_revenue_jan = np.array([2450.67, 1872.34, 1098.44])
company_revenue_feb = np.array([2876.45, 2110.98, 640.78])
print('revenue generated in three company outlets in January =', company_revenue_jan)
print('revenue generated in three company outlets in February =', company_revenue_feb)

revenue generated in three company outlets in January = [2450.67 1872.34 1098.44]
revenue generated in three company outlets in February = [2876.45 2110.98  640.78]


In [147]:
company_revenue_jan + company_revenue_feb

array([5327.12, 3983.32, 1739.22])

Most of these arithmetic operations are not in-place. So, we need to assign the result to a new array if we want to save the result.

In [148]:
sum_arr = company_revenue_jan + company_revenue_feb
sum_arr

array([5327.12, 3983.32, 1739.22])

In [149]:
diff_arr = company_revenue_feb - company_revenue_jan
diff_arr

array([ 425.78,  238.64, -457.66])

In [150]:
company_revenue_jan

array([2450.67, 1872.34, 1098.44])

In [151]:
shifted_arr = company_revenue_jan + 500
shifted_arr

array([2950.67, 2372.34, 1598.44])

In [152]:
v1 = np.array([[5, -4], [-3, 2]])
v2 = np.array([[3, -8], [-6, 0]])

In [153]:
v1

array([[ 5, -4],
       [-3,  2]])

In [154]:
v2

array([[ 3, -8],
       [-6,  0]])

In [155]:
sum_arr = v1 + v2
sum_arr

array([[  8, -12],
       [ -9,   2]])

In [156]:
diff_arr = v1 - v2
diff_arr

array([[2, 4],
       [3, 2]])

In [157]:
v1

array([[ 5, -4],
       [-3,  2]])

In [158]:
sum_arr = v1 + 8
sum_arr

array([[13,  4],
       [ 5, 10]])

In [159]:
sum_arr[0] = sum_arr[0] + 3
sum_arr

array([[16,  7],
       [ 5, 10]])

In [160]:
sum_arr[:, 1] = sum_arr[:, 1] - 5
sum_arr

array([[16,  2],
       [ 5,  5]])

In [161]:
sum_arr[:, 1] = sum_arr[:, 1] + [3, 7]
sum_arr

array([[16,  5],
       [ 5, 12]])

### Example
Performing multiplication and division with arrays

In [162]:
new_arr = np.array([[0, 25, 45], [10, 16, 8], [4, 0, 12]])
new_arr

array([[ 0, 25, 45],
       [10, 16,  8],
       [ 4,  0, 12]])

In [163]:
new_arr = new_arr * 2
new_arr

array([[ 0, 50, 90],
       [20, 32, 16],
       [ 8,  0, 24]])

In [164]:
new_arr[:2, :] = new_arr[:2, :] * 2
new_arr

array([[  0, 100, 180],
       [ 40,  64,  32],
       [  8,   0,  24]])

In [165]:
new_arr / 5

array([[ 0. , 20. , 36. ],
       [ 8. , 12.8,  6.4],
       [ 1.6,  0. ,  4.8]])

In [166]:
rates_of_items = np.array([12, 22, 35])
rates_of_items

array([12, 22, 35])

In [167]:
number_of_items = np.array([100, 50, 40])
number_of_items

array([100,  50,  40])

In [168]:
rates_of_items * number_of_items

array([1200, 1100, 1400])

In [169]:
v1

array([[ 5, -4],
       [-3,  2]])

In [170]:
v2

array([[ 3, -8],
       [-6,  0]])

In [171]:
v1 * v2

array([[15, 32],
       [18,  0]])

### Example
Let us consider the following example for array multiplication:
```
arr_1 = np.array([[1, 3], [-2, 5], [6, 7]])
arr_2 = np.array([[1, -7], [0, 8], [4, -3]])
```
We will see how to multiply the two arrays to produce the following array:
```
np.array([[10, -210], [0, 400], [240, -210]])
```
We might need to scale up the values accordingly by multiplying by a factor

In [172]:
arr_1 = np.array([[1, 3], [-2, 5], [6, 7]])
arr_2 = np.array([[1, -7], [0, 8], [4, -3]])
arr_1 * arr_2 * 10

array([[  10, -210],
       [   0,  400],
       [ 240, -210]])

### Quiz
Consider the arrays shown below:
```
arr_1 = np.array([[0, 4.5], [-2, 1], [-3, 2]])
arr_2 = np.array([[1, -1], [0.5, 4.8], [9, -1.3]])
```
Multiply the two arrays to produce the following array:
```
np.array([[0, -0.9], [-0.2, 0.96], [-5.4, -0.52]])
```
Scale down the values accordingly by dividing by a factor

In [173]:
##### CODE HERE #####

### Example
Performing exponentiation with arrays

In [174]:
np_arr = np.array([[1, 0, 5], [0.5, 3, 7]])
np_arr

array([[1. , 0. , 5. ],
       [0.5, 3. , 7. ]])

In [175]:
np_arr = np_arr ** 2
np_arr

array([[ 1.  ,  0.  , 25.  ],
       [ 0.25,  9.  , 49.  ]])

In [176]:
np_arr = np_arr ** 0.5
np_arr

array([[1. , 0. , 5. ],
       [0.5, 3. , 7. ]])

In [177]:
np_arr = np_arr ** 2
np_arr

array([[ 1.  ,  0.  , 25.  ],
       [ 0.25,  9.  , 49.  ]])

In [178]:
np.sqrt(np_arr)

array([[1. , 0. , 5. ],
       [0.5, 3. , 7. ]])

We have used a NumPy method here called `numpy.sqrt()`. You will learn more about NumPy functions later in the session.

# Dimensional Operations
This section involves performing operations on NumPy arrays that operate along its dimensions.

### Example
Operations along axes

In [179]:
company_revenue_jan = np.array([2450.67, 1872.34, 1098.44])
company_revenue_jan

array([2450.67, 1872.34, 1098.44])

In [180]:
company_revenue_jan.sum()

5421.450000000001

In [181]:
company_revenue_jan.mean()

1807.1500000000003

In [182]:
sample_array = np.array([[2, 25, 45], [10, 16, 8], [4, 3, 12]])
sample_array

array([[ 2, 25, 45],
       [10, 16,  8],
       [ 4,  3, 12]])

In [183]:
sample_array.sum()

125

In [184]:
sample_array.sum(axis = 0)

array([16, 44, 65])

In [185]:
sample_array.sum(axis = 1)

array([72, 34, 19])

In [186]:
sample_array

array([[ 2, 25, 45],
       [10, 16,  8],
       [ 4,  3, 12]])

In [187]:
sample_array.prod()

414720000

In [188]:
sample_array.prod(axis = 0)

array([  80, 1200, 4320])

In [189]:
sample_array.prod(axis = 1)

array([2250, 1280,  144])

In [190]:
sample_array.mean()

13.88888888888889

In [191]:
sample_array.mean(axis = 0)

array([ 5.33333333, 14.66666667, 21.66666667])

In [192]:
sample_array.mean(axis = 1)

array([24.        , 11.33333333,  6.33333333])

### Quiz
Suppose you have the coordinates of two points in 3D space as follows:
```
point1 = np.array([-2, 3, 5])
point2 = np.array([1, 0, -4])
```
Find the distance between these points using the Euclidean distance. Feel free to use a combination of operations and methods to perform this task.

In [193]:
##### CODE HERE #####

In [194]:
##### CODE HERE #####

In [195]:
##### CODE HERE #####

# Miscellaneous Methods
This section included operations that demonstrate a variety of NumPy functionalities.

### Example
Importance of `.reshape()` and `.T` or `.transpose()` methods

In [196]:
np_arr = np.array([[1, 2, 3, 4], [-4, -3, -2, -1]])
np_arr

array([[ 1,  2,  3,  4],
       [-4, -3, -2, -1]])

In [197]:
# np.append(np_arr, 0, axis = 0)

In [198]:
new_arr = np.array([-5, 2, 5, 7])
new_arr

array([-5,  2,  5,  7])

In [199]:
# np.append(np_arr, new_arr, axis = 0)

In [200]:
new_arr.shape

(4,)

In [201]:
np_arr.shape

(2, 4)

We need to use the `.reshape()` method to handle this.

In [202]:
new_arr.reshape(1, 4)

array([[-5,  2,  5,  7]])

In [203]:
new_arr

array([-5,  2,  5,  7])

Notice that reshaping is not in-place.

In [204]:
new_arr = new_arr.reshape(1, 4)
new_arr

array([[-5,  2,  5,  7]])

In [205]:
new_arr.shape

(1, 4)

In [206]:
np_arr = np.append(np_arr, new_arr, axis = 0)
np_arr

array([[ 1,  2,  3,  4],
       [-4, -3, -2, -1],
       [-5,  2,  5,  7]])

In [207]:
np_arr.shape

(3, 4)

In [208]:
new_arr = np.array([[2], [-3], [4]])
new_arr

array([[ 2],
       [-3],
       [ 4]])

In [209]:
new_arr.shape

(3, 1)

In [210]:
np_arr = np.append(np_arr, new_arr, axis = 1)
np_arr

array([[ 1,  2,  3,  4,  2],
       [-4, -3, -2, -1, -3],
       [-5,  2,  5,  7,  4]])

In [211]:
np_arr.shape

(3, 5)

In [212]:
new_arr = np.array([[5, 9], [-4, -2], [7, 1]])
new_arr

array([[ 5,  9],
       [-4, -2],
       [ 7,  1]])

In [213]:
new_arr.shape

(3, 2)

In [214]:
np_arr = np.append(np_arr, new_arr, axis = 1)
np_arr

array([[ 1,  2,  3,  4,  2,  5,  9],
       [-4, -3, -2, -1, -3, -4, -2],
       [-5,  2,  5,  7,  4,  7,  1]])

In [215]:
np_arr.shape

(3, 7)

In [216]:
new_arr = np.array([[8, 4, -3, 4, -6, 8, 0], [-4, 1, 1, -5, 7, -3, -2], [-5, 2, -6, 3, 3, 4, 2]])
new_arr

array([[ 8,  4, -3,  4, -6,  8,  0],
       [-4,  1,  1, -5,  7, -3, -2],
       [-5,  2, -6,  3,  3,  4,  2]])

In [217]:
new_arr.shape

(3, 7)

In [218]:
np_arr = np.append(np_arr, new_arr, axis = 0)
np_arr

array([[ 1,  2,  3,  4,  2,  5,  9],
       [-4, -3, -2, -1, -3, -4, -2],
       [-5,  2,  5,  7,  4,  7,  1],
       [ 8,  4, -3,  4, -6,  8,  0],
       [-4,  1,  1, -5,  7, -3, -2],
       [-5,  2, -6,  3,  3,  4,  2]])

In [219]:
np_arr.shape

(6, 7)

You are encouraged to study the `.reshape()` method in further detail along with the `shape` attribute. The shape of an array is arguably its most important attribute which forms the basis for all operations and methods built on top of arrays.

Other methods of interest here are the `.transpose()` or the `.T` method, the `.flatten()` method, and other related methods.

### Example
Rounding

In [220]:
np_arr = np.array([1.56, 2.765, -3.33, 5.102, 6.6464])
np_arr

array([ 1.56  ,  2.765 , -3.33  ,  5.102 ,  6.6464])

In [221]:
np_arr = np.round(a = np_arr, decimals = 2)
np_arr

array([ 1.56,  2.76, -3.33,  5.1 ,  6.65])

In [222]:
np_arr = np.round(np_arr)
np_arr

array([ 2.,  3., -3.,  5.,  7.])

### Example
Generating numerical pattern arrays

In [223]:
np.arange(start = 0, stop = 5, step = 1)

array([0, 1, 2, 3, 4])

The `numpy.arange()` method is similar to Python's built-in `range()` function but returns a NumPy array instead of a list. It generates values in a given range with a specified step size.

In [224]:
np.arange(-10, 0, 0.5)

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [225]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [226]:
np.arange(0, 0.55, 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [227]:
np.linspace(start = 0, stop = 1, num = 2)

array([0., 1.])

The `numpy.linspace()` generates a specific number of evenly spaced values over a specified range. It is useful when you want to ensure that the range includes both the start and the end values.

In [228]:
np.linspace(start = 0, stop = 1, num = 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [229]:
np.linspace(start = 0, stop = 1, num = 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [230]:
np.linspace(start = 0, stop = 1, num = 51)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ])

### Quiz
Define a function called `show_ap()` that takes in the first term and the common difference of an arithmetic progression and prints the first $n$ terms of the sequence.

Here is a test case to help you out:
> The output of `show_ap(5, 3, 6)` should be `np.array([5, 8, 11, 14, 17, 20])`.

In [231]:
##### CODE HERE #####

### Example
Random number generation

In [232]:
np.random.randint(low = 1, high = 5, size = 10)

array([2, 1, 1, 3, 2, 1, 3, 1, 1, 3])

In [233]:
np.random.randint(low = -10, high = 16, size = 1)

array([14])

In [234]:
np.random.rand()

0.32699475635873787

In [235]:
np.random.rand(2, 3)

array([[0.22759433, 0.56946222, 0.75455709],
       [0.4625302 , 0.97722661, 0.11742942]])

In [236]:
np.random.rand(4, 2)

array([[0.59975315, 0.90995785],
       [0.88584981, 0.70828871],
       [0.52620628, 0.63576759],
       [0.60693562, 0.39796215]])

The random number generation methods within NumPy are vast and many. You are encouraged to explore this further on your own. You will also study distributions in greater detail later.

### Example
Maximum and minimum values

In [237]:
monthly_rates = np.array([[0, 25, 45], [10, 16, 8], [4, 2, 12]])
monthly_rates

array([[ 0, 25, 45],
       [10, 16,  8],
       [ 4,  2, 12]])

In [238]:
monthly_rates.max()

45

In [239]:
monthly_rates.min()

0

In [240]:
monthly_rates[0].min()

0

In [241]:
monthly_rates[:, 1].max()

25

In [242]:
monthly_rates.max(axis = 0)

array([10, 25, 45])

In [243]:
monthly_rates.min(axis = 1)

array([0, 8, 2])

In [244]:
monthly_rates

array([[ 0, 25, 45],
       [10, 16,  8],
       [ 4,  2, 12]])

In [245]:
np.argmax(monthly_rates)

2

In [246]:
np.argmin(monthly_rates, axis = 0)

array([0, 2, 1])

In [247]:
np.argmax(monthly_rates, axis = 1)

array([2, 1, 2])

### Example
Mathematical constants

In [248]:
np.pi

3.141592653589793

In [249]:
np.e

2.718281828459045

In [250]:
np.nan

nan

In this section, we looked at some basic and important operations involving NumPy arrays, such as mathematical and statistical operations. Another thing to note is that NumPy does offer a `numpy.matrix()` class, but `numpy.array()` does everything that `numpy.matrix()` does and more, so it is the more popular choice. To learn more about `numpy.matrix()`, you can checkout the offical documentation [link](https://https://numpy.org/doc/stable/reference/generated/numpy.matrix.html).